#!/bin/sh

docker exec -it webscale-bandits_kafka_1 kafka-console-consumer.sh \
  --bootstrap-server kafka:9092 \
  --topic test-out \
  --from-beginning \
  --formatter kafka.tools.DefaultMessageFormatter \
  --property print.key=true \
  --property print.value=true \
  --property key.deserializer=org.apache.kafka.common.serialization.StringDeserializer \
  --property value.deserializer=org.apache.kafka.common.serialization.LongDeserializer
